### ISSUE TITLE
Project 1 - Personal Portfolio

### ISSUE THREAD

**Issue by camerican** [camerican/NYCDA_SCC16_Jean#6]
The personal portfolio has the following criteria:
- [x] At least 3 separate pages +
- [x] Connected by a consistent navigation menu (3)
- [ ] Uses CSS layout principles, with design-friendly whitespace (6)
- [x] Includes images (2)
- [ ] Has links to external websites that open in a new window
- [ ] Incorporates a ul and nav powered navigation bar (2)
- [ ] Overall quality of the site (3)
- [x] Is well committed and pushed to GitHub (3)

**Comment by camerican** [comment]
Hi Jean, while your site meets several of the requirements of the portfolio project, several areas could use attention.  It would be great if you're able to continue working on this now that the course has concluded!
- [ ] Redevelop homepage to fill whitespace #10
- [ ] External links should open in new page #12
- [ ] Use unordered list in nav #13

In addition, there are the following notes below of other items you could work on:
- [ ] Fallback font families should be consistent #7 
- [ ] Avoid use of justify around anchors/links #8 
- [ ] Remove unnecessary mark-up #9 
- [ ] Remove lorem ipsum from infotech.html #11
